### ISSUE TITLE
Question using themes aside from VOIDX

### ISSUE THREAD

**Issue by antonioOrtiz** [synapticism/wordpress-gulp-starter-kit#17]
Hey thanks for making a much needed workflow/tool! I had a question for you...From what I read in the docs, and your blog post, one should be able to swap out `VOIDX:` for another theme, is that correct? 

Right now i'd like to use the [getbeans](http://www.getbeans.io/documentation/uikit-in-beans/) theme in place of `voidx`. So far when I fire up the `gulp` task the site opens up with the `getbeans` theme and the tasks are firing, however nothing is updating in the browser.

I changed the following:

In the `gulpconfig`

    var project     = 'tm-beans-child'
    , src         = './src/'
    , build       = './tm-beans-child/'
    , dist        = './dist/'+project+'/'
    , bower       = './bower_components/'
    , composer    = './vendor/'
    , modules     = './node_modules/'
    ;

And I `symlinked` the new 'tm-beans-child' i.e. build folder into the wp/themes folder folder like so:

![screen shot 2015-10-25 at 7 22 46 pm](https://cloud.githubusercontent.com/assets/4282013/10718635/14366d60-7b4e-11e5-9a65-3add4f04ee64.png)

to here:

![screen shot 2015-10-25 at 7 23 11 pm](https://cloud.githubusercontent.com/assets/4282013/10718637/18616fe8-7b4e-11e5-9268-c28d9ee1d7bb.png)

Any help would be swell!

**Comment by Annalyn** [comment]
I noticed that your tm-beans-child is a different folder from src.  All your files and folders inside your child theme should be included in your src folder.

**Comment by synapticism** [comment]
When you run `gulp` do you see files appear in `tm-beans-child`? If you do then it's probably a symlinking issue... if not, you probably need to fiddle around with the glob patterns matching files under `src`. But yes, you should be able to swap out the default theme and use whatever you like with minimal configuration.

**Comment by synapticism** [comment]
I had a quick look at the Beans theme and it seems like you can do a straight substitution; delete everything under `src` and swap things in. Shouldn't be a problem after that.

**Comment by antonioOrtiz** [comment]
Hey thanks! Things are updating perfectly!
