### ISSUE TITLE
Normalize libsass

### ISSUE THREAD

**Issue by dbox** [synapticism/wordpress-gulp-starter-kit#18]
Might be worth using this, just to avoid the hacky gulp stuff to bring in a css file:

https://github.com/krisbulman/normalize-libsass

**Comment by synapticism** [comment]
Thanks, this looks cool. My only reservation has to do with maintenance; despite the use of a hack to import the file I'm still going straight to the source whereas you never really know when someone's going to abandon a port that hasn't yet become hugely popular... so I'll leave this issue open for a bit and mull it over.

**Comment by dbox** [comment]
Understood! Just seems like normalize isn't really going to do much changing at this point, so even if they abandon probably not a huge deal. Your call. :)

**Comment by synapticism** [comment]
After some thought I decided to leave this out for the time being (though I made a reference in the readme). It just adds one more thing for new users to try and wrap their heads around and I'm trying to keep this simple :)
