### ISSUE TITLE
First install..

### ISSUE THREAD

**Issue by IronAddict** [synapticism/wordpress-gulp-starter-kit#19]
Any idea why I am getting a bunch of Python installation errors. What am I missing that I need to install manually?

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd R:\wordpress\apps\wordpress\htdocs\wp-content\themes\wordpress-gulp-starter-kit\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by Annalyn** [comment]
Are you using Mac and have updated the installed Python?  If you reinstall Python 2.7 that error will go away.

**Comment by IronAddict** [comment]
I am on a Windows 10 system. Never had to install Python on any of the other Gulp / Wordpress installs and nothing was jumping out to me in the gulpfile that uses it, not to mention the readme never mentioned it. I was really hoping this was going to be the one for me, it is proving to be a lot more tedious than I anticipated using Wordpress/Gulp/SASS

**Comment by Annalyn** [comment]
Hi Jay,  I think you have the same issue as this one: http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm.  

Once the installation problem resolved, believe me this starter kit is going to be a great addition to your workflow.

**Comment by IronAddict** [comment]
Thank you Annalyn, I hadn't seen that thread but was checking some others with the same solutions (only this one is written better) I just feel like I am installing so many modules, apps, programs and etc it's all losing sight of the purpose. I was serious when I said I hoped this one from synapticism was "the one" because I liked the way he wrote the readme and I understood almost all of it and there was recent updates. Coming from someone who just hacked away at css prior and still wants to use the Genesis framework is almost becoming counter-productive, it seems there are so many ways of doing things I am also losing focus. I started down this path incorporating SASS, Gulp and so on after getting a taste playing with FoundationPress a little...that was 2 weeks ago and now my head is just spinning.

Anyway, enough whining thank you for the reply and I will try not to give up on this task.

**Comment by IronAddict** [comment]
So am I thinking about this correctly, that I should (with some customization and modification) be able to use this "kit" with any theme I want? When I see scaffolding mentioned, I think about this being possible and the goal rather than starting over from scratch with every new site.

I admit now I am having some issue wrapping my head around the config file included and what is the <i>best practice</i> of how to get it to work in a dev environment without doing a build or distribution. Although, I also believe I may be confusing myself by reading so many sites and trying so many different gulp & grunt users installs.

**Comment by synapticism** [comment]
Yes, the idea is that you can use this scaffolding kit with whatever theme you want. Rip out the included theme, put your own in the `src` directory, check to make sure that all the paths in the configuration file are correct, and you should be good to go if you've got all the underlying software correctly installed.

Sounds like you're chugging through the nitty gritty (not unsurprising on Windows 10 since a lot of the Node ecosystem stuff is made with OS X as a dev environment in mind) so keep going... one thing I will point out is that doing a build is the whole point of using Gulp. You take raw material, run Gulp, and it'll build a theme with everything in the right place. The build is what you will be testing out in your local development environment as you tweak and modify your theme. The distribution is what you will upload to your server when it's ready to blast.

**Comment by synapticism** [comment]
I've updated the project and fleshed out the documentation a little bit. Feel free to post here again if you're still having some trouble but I'm going to close this issue for now.
