### ISSUE TITLE
Mixin won't accept @content block using libsass compiler

### ISSUE THREAD

**Issue by lxm7** [synapticism/wordpress-gulp-starter-kit#21]
http://stackoverflow.com/questions/33669953/mixin-wont-accept-content-block-with-libsass

Posted here on stackoverflow, I believe it's something in the config I need to change but not sure where exactly, works fine with all other tools. Any suggestions would be great. I'm on Windows 10. Thanks

**Comment by synapticism** [comment]
@lxm7 Are you using the most recent version? I also encountered this problem and put a fix in. Let me know if it's still an issue for you and I'll get to the bottom of it.

**Comment by lxm7** [comment]
Thanks for getting back. It's now fixed. Cheers
