### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by socheon** [synapticism/wordpress-gulp-starter-kit#24]
When I run gulp, I get the following 

[22:40:35] Starting 'scripts-minify'...

.../wordpress-gulp-starter-kit/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined

**Comment by benjdl** [comment]
Updating node.js should resolve your issue.

**Comment by synapticism** [comment]
See above! Let me know if your problem persists after cleaning out your environment and updating everything.
