### ISSUE TITLE
npm install jshint dependency problem

### ISSUE THREAD

**Issue by guidstah** [synapticism/wordpress-gulp-starter-kit#25]
Hi, trying to get this working on Mint 17.2 (based on Ubuntu), would love to try something simpler than Sage.

When running 'npm install' after editing the gulpcnfig.js to name my theme 'test' I get the following output:

`npm WARN lifecycle wordpress-gulp-starter-kit@0.2.0~postinstall: cannot run in wd %s %s (wd=%s) wordpress-gulp-starter-kit@0.2.0 gulp setup /home/guido/Development/Wordpress/Gulpstarter
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN gulp-jshint@2.0.0 requires a peer of jshint@2.x but none was installed.`

Doesn't matter if sudo or not... Any ideas what the problem is? Or how to solve it?

**Comment by guidstah** [comment]
Alright, figured it out... wordpress-gulp-starter-kit is working for me now. It seems that there was a dependancy problem of the gulp-jshint package, which needs jshint. According to the maintainer of gulp-jshint the problem seems to be that jshint pushed a release candidate to npm, which broke a lot of stuff.
https://github.com/spalger/gulp-jshint/issues/131

2.8.0 seems to be the right version of jshint.

Temporary workarround I used, was adding the jshint dependency to package.json of wordpress-gulp-starter-kit. Like this:
`    "jshint": "2.8.0",`
And then run the npm install command again. What should work as well:
`npm --save-dev jshint@2.8.0`

I know this isn't pretty but it works. Hope someone can use this. Now I'm off to try out the sweet stuff!

**Comment by synapticism** [comment]
I think you might also be able to install jshint globally, no? At any rate, this will be cleared up soon enough :)

**Comment by DanielTate** [comment]
Thanks @guidstah 

    npm install --save-dev jshint@2.8.0

**Comment by synapticism** [comment]
I added jshint to the project dependencies as per documentation update of gulp-jshint. Should be okay now, let me know if it's not.

**Comment by manoj30dec** [comment]
npm install --save-dev jshint@2.8.0 worked in my case..
