### ISSUE TITLE
browsersync not displaying anything

### ISSUE THREAD

**Issue by gamalardi** [synapticism/wordpress-gulp-starter-kit#26]
Thanks for the awesome starter kit! but I'm have an issue where when I try gulp with browsersync, its not displaying anything. 

I did change the livereaload to browsersync, modifying the port but its still not working. Do you have any idea why?

sorry, i'm still a newbie for this kind of stuff.

**Comment by synapticism** [comment]
@gamalardi Hey, did you configure BrowserSync? You need to set the local proxy since there's server-side rendering going on here.

**Comment by jarekpelczynski** [comment]
Have same problem. Livereload is working, but not BrowserSync (nothing is displayed on the Gulp console). 

I use build-in server in PHP (php -S 127.0.0.1:8000), I set proxy to 127:0.0.1:8000 in Gulp config.

**Comment by synapticism** [comment]
I just checked and browsersync is working fine for me. Be sure to set the proxy to your local web server address. I'm going to close this but if you're still having some trouble feel free to submit more information here.
