### ISSUE TITLE
Problem with dist folder when uploading to a production server.

### ISSUE THREAD

**Issue by antonioOrtiz** [synapticism/wordpress-gulp-starter-kit#29]
I am working locally and at a point where i'd like to begin to start to check things out on the PROD server. However, what I push to PROD appears broken and essentially a mess! 

Is there something I am missing from the documentation to load a site to PROD?

Here is what I have developed locally ==> https://antonioportiz.fwd.wf

And here is what I have tried to push to the PROD server ==> http://37.60.247.225/~montes69/

Any help would be aprreciated!

**Comment by antonioOrtiz** [comment]
So I went back to the documentation just to make sure I didn't miss anything. 

One doesn't need the `src/inc/assets.php` and `functions.php and functions-config-defaults.php` in order to have your theme to work in PROD. That's what you'd use if you're using the 'voidx' right?

I can't find anything in the configurable files which would be causing such a stark difference from what I have developed locally https://antonioportiz.fwd.wf and what is sitting on the production server http://37.60.247.225/~montes69/

**Comment by synapticism** [comment]
I don't see anything on the main URL so I can't help you out... but there shouldn't be any special problems affecting the production-version. Compare your local `build` and `dist` copies and see if some file specific to your theme did not copy over for some reason. 

I'll also be updating the project to a new version soon so you may wish to check out the `develop` branch.

**Comment by antonioOrtiz** [comment]
Thanks, turns out error was elsewhere!
