### ISSUE TITLE
Gulp watch

### ISSUE THREAD

**Issue by Budolfsen** [synapticism/wordpress-gulp-starter-kit#32]
This starter-kit is awesome - have used on a couple of projects now and love the simplicity of it - but I have a problem....

I have removed the theme it comes with at put in my own using underscore - but when I add files (sass, php or js) it doesn't fire the gulp task a copy the files to build folder.

I then have to edit an existing file then it copies them - but when I make changes to the new files it doesn't run browsersync and updates browser - again then I have to save another files (sass, js or php) to get it to refresh.

I have add the plumber plugin so gulp doesn't halt on errors - but other than that no changes to your setup.

Hope you have a fix to this problem - so I don't need to install gulp-watch plugin....:)

**Comment by synapticism** [comment]
Hey, I'm glad you find this project useful :) 

Have you modified your `gulpconfig.js` to match your new setup? There is a section for `watch` that might need to be changed around... plus, of course, the directory definitions at the top of the file. If these things are all correct then I'm not really sure what the problem could be without you posting your config file and a screenshot of the directory structure of the `src` folder.

**Comment by Budolfsen** [comment]
[files.zip](https://github.com/synapticism/wordpress-gulp-starter-kit/files/152652/files.zip)
I believe I have changed it all correctly -but I have uploaded both my gulp-files and the src folder as a zip-file for you

**Comment by synapticism** [comment]
Would you mind sharing the config in fenced-code blocks and posting a *screenshot* of your folder structure? I don't want to have to download something to my local environment, sorry.

**Comment by Budolfsen** [comment]
Here is the configfile
`// ==== CONFIGURATION ==== //

// Project paths
var project     = 'broenderslevhandel'    // The directory name for your theme; change this at the very least!
  , src         = './src/'                // The raw material of your theme: custom scripts, SCSS source files, PHP files, images, etc.; do not delete this folder!
  , build       = './build/'              // A temporary directory containing a development version of your theme; delete it anytime
  , dist        = './dist/'+project+'/'   // The distribution package that you'll be uploading to your server; delete it anytime
  , assets      = './assets/'             // A staging area for assets that require processing before landing in the source folder (example: icons before being added to a sprite sheet)
  , bower       = './bower_components/'   // Bower packages
  , composer    = './vendor/'             // Composer packages
  , modules     = './node_modules/'       // npm packages
;

// Project settings
module.exports = {

  browsersync: {
    files: [build+'/**', '!'+build+'/**.map'] // Exclude map files
  , notify: false // In-line notifications (the blocks of text saying whether you are connected to the BrowserSync server or not)
  , open: true // Set to false if you don't like the browser window opening automatically
  , port: 3000 // Port number for the live version of the site; default: 3000
  , proxy: project+'.dev' // We need to use a proxy instead of the built-in server because WordPress has to do some server-side rendering for the theme to work
  , watchOptions: {
      debounceDelay: 2000 // This introduces a small delay when watching for file change events to avoid triggering too many reloads
    }
  },

  images: {
    build: { // Copies images from `src` to `build`; does not optimize
      src: src+'**/*(*.png|*.jpg|*.jpeg|*.gif|*.svg)'
    , dest: build
    }
  , dist: {
      src: [dist+'**/*(*.png|*.jpg|*.jpeg|*.gif|*.svg)', '!'+dist+'screenshot.png'] // The source is actually `dist` since we are minifying images in place
    , imagemin: {
        optimizationLevel: 7
      , progressive: true
      , interlaced: true
      }
    , dest: dist
    }
  },

  livereload: {
    port: 35729 // This is a standard port number that should be recognized by your LiveReload helper; there's probably no need to change it
  },

  scripts: {
    bundles: { // Bundles are defined by a name and an array of chunks (below) to concatenate; warning: this method offers no dependency management!
      core: ['core']
    , pageloader: ['pageloader', 'core']
    }
  , chunks: { // Chunks are arrays of paths or globs matching a set of source files; this way you can organize a bunch of scripts that go together into pieces that can then be bundled (above)
      // The core chunk is loaded no matter what; put essential scripts that you want loaded by your theme in here
      core: [
      src+'js/classie.js'
      , src+'js/leftmenu.js'
      , src+'js/video.js'
      ]
      // The pageloader chunk provides an example of how you would add a user-configurable feature to your theme; you can delete this if you wish
      // Have a look at the `src/inc/assets.php` to see how script bundles could be conditionally loaded by a theme
    , pageloader: [
        modules+'html5-history-api/history.js' // The modules directory contains packages downloaded via npm
      , modules+'spin.js/spin.js'
      , modules+'spin.js/jquery.spin.js'
      , modules+'wp-ajax-page-loader/wp-ajax-page-loader.js'
      , src+'js/page-loader.js'
      ]
    }
  , dest: build+'js/' // Where the scripts end up in your theme
  , lint: {
      src: [src+'js/**/*.js'] // Linting checks the quality of the code; we only lint custom scripts, not those under the various modules, so we're relying on the original authors to ship quality code
    }
  , minify: {
      src: [build+'js/**/*.js', '!'+build+'js/**/*.min.js'] // Avoid recursive min.min.min.js
    , rename: { suffix: '.min' }
    , uglify: {} // Default options
    , dest: build+'js/'
    }
  , namespace: 'wp-' // Script filenames will be prefaced with this (optional; leave blank if you have no need for it but be sure to change the corresponding value in `src/inc/assets.php` if you use it)
  },

  styles: {
    build: {
      src: src+'sass/**/*.sass'
    , dest: build
    }
  , compiler: 'libsass' // Choose a Sass compiler: 'libsass' or 'rubysass'
  , autoprefixer: { browsers: ['> 3%', 'last 2 versions', 'ie 9', 'ios 6', 'android 4'] } // This tool is magic and you should use it in all your projects :)
  , minify: { safe: true }
  , rubySass: { // Requires the Ruby implementation of Sass; run `gem install sass` if you use this; Compass is *not* included by default
      loadPath: ['./src/sass', bower, modules] // Adds Bower and npm directories to the load path so you can @import directly
    , precision: 6
    , sourcemap: true
  }
  , libsass: { // Requires the libsass implementation of Sass (included in this package)
      includePaths: ['./src/sass', bower, modules] // Adds Bower and npm directories to the load path so you can @import directly
    , precision: 6
    , onError: function(err) {
        return console.log(err);
      }
    }
  },

  theme: {
    lang: {
      src: src+'languages/**/*' // Glob pattern matching any language files you'd like to copy over; we've broken this out in case you want to automate language-related functions
    , dest: build+'languages/'
    }
  , php: {
      src: src+'**/*.php' // This simply copies PHP files over; both this and the previous task could be combined if you like
    , dest: build
    }
  },

  utils: {
    clean: [build+'**/.DS_Store'] // A glob pattern matching junk files to clean out of `build`; feel free to add to this array
  , wipe: [dist] // Clean this out before creating a new distribution copy
  , dist: {
      src: [build+'**/*', '!'+build+'**/*.map']
    , dest: dist
    }
  , normalize: { // Copies `normalize.css` from `node_modules` to `src/sass` and renames it to allow for it to imported as a Sass file
      src: modules+'normalize.css/normalize.css'
    , dest: src+'sass'
    , rename: '_normalize.sass'
    }
  },

  watch: { // What to watch before triggering each specified task; if files matching the patterns below change it will trigger BrowserSync or Livereload
    src: {
      styles:       src+'sass/**/*.sass'
    , scripts:      src+'js/**/*.js' // You might also want to watch certain dependency trees but that's up to you
    , images:       src+'images/**/*(*.png|*.jpg|*.jpeg|*.gif|*.svg)'
    , theme:        src+'**/*.php'
    , livereload:   build+'**/*'
    }
  , watcher: 'browsersync' // Modify this value to easily switch between BrowserSync ('browsersync') and Livereload ('livereload')
  }
}
`
![skaermbillede 2016-03-01 kl 16 01 02](https://cloud.githubusercontent.com/assets/8915971/13430837/0577ee06-dfc7-11e5-943b-6dbc6e0c81bb.png)

**Comment by synapticism** [comment]
OK, and this is a screenshot of `broenderslevhandel/src/`?

**Comment by Budolfsen** [comment]
Yes it is....

**Comment by synapticism** [comment]
OK, don't have any obvious ideas then. I'll take a closer look when I have some time.

**Comment by Budolfsen** [comment]
Sounds good - hope you find a solution.... 
What I can't figure out is why it won't see the new added files even after they are copied....

**Comment by arnisjuraga** [comment]
Bumped in the same problem.
At least with `sass` files - it looks, You must prefix filenames with underscore, to indicate, they are partials.
Now it works:

Look at "EDIT 2" comment here: 
https://github.com/dlmanning/gulp-sass/issues/313#issuecomment-134966039
