### ISSUE TITLE
Change normalize

### ISSUE THREAD

**Issue by malasaad82** [synapticism/wordpress-gulp-starter-kit#38]
I got error message and its about from file style.scss 
@import "normalize";

I fixed it but install node-normalize-scss
npm install node-normalize-scss --save-dev

**Comment by synapticism** [comment]
When you run `npm install` this should automatically trigger `gulp setup` which copies normalize to the appropriate location. If you have some trouble with this step just run `gulp setup` on the command line after installing all dependencies.
