### ISSUE TITLE
PHPStorm problem

### ISSUE THREAD

**Issue by evanre** [synapticism/wordpress-gulp-starter-kit#40]
Hi, thanks for a great starter kit. I have a problem with trying to launch tasks via PHPStorm build in task runner. Console displays every step, but in working folder nothing happens. For example, if I run default task at first time (the build/ folder does not exist yet), it doesn't create anything, browsersync runs, but shows white screen, if i modify any file - watcher ignores it. And there are no any errors or something else.
[screen](https://dl.dropboxusercontent.com/u/27170308/wp-gulp-phpstorm.png)
Version 0.3.0
Windows 10,
PHPStorm 2016.1.2

Thank you.

P.S. With bash\cmd any cli all works fine.

**Comment by evanre** [comment]
I figured out what the problem was. This is `gulpfile.js` folder. PHPStorm Gulp module can't reference to the folder. So I rename file `gulpfile.js/index.js` to `gulpfile.js` and move it to the parent folder. `tasks` folder and `gulpconfig.js` i move to `gulpconfig` folder and fix all paths inside files.

**Comment by synapticism** [comment]
Hmm! Perhaps I am being too fancy with this method. Thanks for the report and I'll think about switching the directory structure around for increased compatibility with other OSes in the future.
