### ISSUE TITLE
wp-ajax-page-loader 0.3

### ISSUE THREAD

**Issue by gethinoakes** [synapticism/wordpress-gulp-starter-kit#44]
Hi, first - thanks for a great repo!

I see you updated wp-ajax-page-loader to 0.3, but I just had to roll it back to 0.2.1 as it was preventing npm install

From terminal:
Valid install targets: ["0.1.3","0.2.0","0.2.1"]

**Comment by synapticism** [comment]
Sorry, forgot to hit `npm publish` on that package. It's available now, please update.
