### ISSUE TITLE
use jscs instead of jshint

### ISSUE THREAD

**Issue by 6zz** [synapticism/wordpress-gulp-starter-kit#47]
I think with jscs it is closer to checking against wordpress js coding standards.  I found this preset with jscs linter: https://github.com/jscs-dev/node-jscs/blob/master/presets/wordpress.json

**Comment by synapticism** [comment]
JSCS is deprecated but I'll look into ESLint.

**Comment by synapticism** [comment]
@6zz I have a working integration of ESLint with at least some WP coding standards on the develop branch; you're welcome to take a look and give some feedback while testing proceeds. https://github.com/synapticism/wordpress-gulp-starter-kit/tree/develop

**Comment by 6zz** [comment]
@synapticism wordpress has defined its [js coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/) using JSCS, I was able to get pretty close to matching it.  With ESLint though, it might be a bit tougher because we might use `let` and `const` instead of `var`.

**Comment by synapticism** [comment]
JSCS or JSHint? I perused that link and it seems like this is the file they suggest checking against:
https://develop.svn.wordpress.org/trunk/.jshintrc

It makes sense for this project to adhere to the same standards if it's not too much trouble... so I'm hoping to be clear on what we're looking for here.

**Comment by 6zz** [comment]
sorry for the late reply.  it's just that with jshint, it is not able to enforce some of the js standards wordpress defined. Such as “Yoda” Conditions, but achievable with JSCS.

**Comment by synapticism** [comment]
Ah, okay. It seems like the WP team is still on JSHint despite it not being able to apply some of their own coding standards then. Anyway, I gotta take some time to look at this more closely now.

**Comment by 6zz** [comment]
np.  I actually do not like the js standards set by the wp team because I was influenced by Douglas Crockford's "javascript the good parts".  :)  Also, I hope the wp team jump on the es6 bandwagon soon now that es6 transpilers are pretty prevalent.

**Comment by synapticism** [comment]
Yeah, personally I find those standards make for less readable and maintainable code so I don't follow them in any of my projects (none of which end up in the theme/plugin directory so I have that luxury)... which is why I'm a little `???` about this whole subject :)

**Comment by 6zz** [comment]
ahh...agreed.  let's just drop it. :D
