### ISSUE TITLE
background image URL

### ISSUE THREAD

**Issue by millman2394** [synapticism/wordpress-gulp-starter-kit#48]
Hello, 

How should I go about placing background images in style.scss? 

The only way I can get it to work it to put a very long url such as: 

`url(/my-wordpress-install/wp-content/themes/mytheme/build/images/background/blue-wood.jpg)`

If I put  `../images/bg.jpg"`

it will almost give me the full url, except instead of `/build/images, it will append %289-18%29/images/`

EDIT:

When I have background:url in a partial scss file, the error occurs.

**Comment by evanre** [comment]
You need to put url according to your style.css in theme folder. So if you have picture in `..../themes/yourtheme/images/bg.jpg` your css code must be: `url(images/bg.jpg)`.

**Comment by millman2394** [comment]
Thanks for the reply. 

I could have sworn I did that a million times. Now it's working...

welp...Thank you very much!

**Comment by millman2394** [comment]
Now I remember what the issue was. I have a URL in my partial file. When I do the URL like above, it doesn't work.

**Comment by evanre** [comment]
What is your files structure?

**Comment by millman2394** [comment]
Inside my src/scss I have:

a partial folder with a couple partials and inside that folder I have a sections folder.

scss/partials/sections
scss/partials/blog
scss/partials/shop

I figured since I'm importing them all into one file, the URL should be the same no matter the nested file structure.

**Comment by evanre** [comment]
No, whole project: src, build, theme etc.

**Comment by millman2394** [comment]
Root:
http://imgur.com/K0P8q9W

src:
http://imgur.com/exi6vbz

build:
http://imgur.com/m3HNwbQ

**Comment by evanre** [comment]
Where in wordpress this folder(root) is placed and how you "link" build folder in themes?

**Comment by millman2394** [comment]
`xampp/htdocs/(wordpress-install)/wp-content/themes/(wordpress-gulp-starter-kit theme)`

I just started using this starter kit. I didn't really change anything that was out of the box.

the first time I ran gulp, the theme made the build folder and automatically linked to it. 


also, I will note that the server doesn't actually livereload. I'm not running on localhost:3000 as it says in my gulpconfig because it wouldn't work. I am running through xampp. ie. localhost/(wordpress-install).

**Comment by millman2394** [comment]
sorry, I figured it out. It was really stupid mistake. an image didn't transfer over...

Basically I wasted your time. sorry!!

**Comment by evanre** [comment]
You're welcome) I asking because i don't understand, how wordpress see your theme files in folder `yourtheme/build`. I put all project files and folders in wordpress root folder, and make symbolic link `wordpress/build === wordpress/wp-content/themes/mytheme`. 
[http://imgur.com/a/suqez](http://imgur.com/a/suqez)
