### ISSUE TITLE
How to integrate with theme

### ISSUE THREAD

**Issue by dezinerdudes** [synapticism/wordpress-gulp-starter-kit#49]
Hi there,

I can seem to integrate your starter kit with an existing theme, despite going through your instructions meticulously. Please could you elaborate a bit on this. Simply dropping in the theme files into the src directory does not work.

**Comment by synapticism** [comment]
You'll have to modify a few things to match however your theme is organized and whatever it contains. If you have a link to the theme in question or a screenshot of the directory structure I might be able to help... but there's no way to write instructions for this sort of thing.
