### ISSUE TITLE
JSHint npm error

### ISSUE THREAD

**Issue by RuslanYurchenko** [synapticism/wordpress-gulp-starter-kit#57]
I think will be more useful to provide a JSHint  within npm install. I  installed JSHint global but got an error while run 'npm install' as: Error: Cannot find module 'jshint/src/cli'. 

Command below solved this issue:
npm install --save-dev jshint gulp-jshint

Maybe  no need to install this tool separately.

**Comment by synapticism** [comment]
Yes, I have to review JS hinting/linting as per #47
